### ISSUE TITLE
Cancel or Relocate a Region of Interest

### ISSUE THREAD

**Issue by Jimmydaux** [DroidPlanner/Tower#1267]
From Mission planner, we are able to create a region of interest and then cancel the ROI using an additional ROI point with 0's in all of its parameters. It would be nice to have a mission item that will cancel a current ROI or to switch to a second,third,fourth...... ROI point. With this, it would also be nice to be able to delay activation of an ROI until its associated waypoint. For instance, on a 4 waypoint mission, one would be able to fly from 1 to 2 with No ROI, from 2 to 3 with a newly established ROI, as well as from 3 to 4 with an ROI different than the first.

**Comment by ne0fhyk** [comment]
Fixed by pr #1659
