### ISSUE TITLE
Pre-download maps for areas without mobile internet or just to save $ 

### ISSUE THREAD

**Issue by figwig** [DroidPlanner/Tower#1272]
Hi, I was just wondering whether a feature where you could predownload a map could be added so that when you get there you arnt dependent on there being signal or if you have none left in your monthly contract. That would really be a good feature! Maybe when you're not connected to the drone there could be an option to save the map you're looking at? 
Great work so far, awesome app!
Cheers,
Will

**Comment by ne0fhyk** [comment]
Added in version 3.2.0
