### ISSUE TITLE
Mobius action cam

### ISSUE THREAD

**Issue by FLYBYME** [DroidPlanner/Tower#1290]
Can someone help me out with this information.

Its for the mobius narrow cam.

```
<Name>Mobius Action Cam</Name>
<SensorWidth>???</SensorWidth>
<SensorHeight>???</SensorHeight>
<SensorResolution>2304×1536</SensorResolution>
<FocalLength>???</FocalLength
```

**Comment by Geo-Trackers** [comment]
I think the information you have regarding focal length for Lens  A --> 87 degree FOV is incorrect, it should be rather 4.957 mm.  The mobius sensor size --> (1/2.7") , We have the formula for Focal Length as:
f = (1/2.7")* 25.4 / (2 tan (FOV/2)) mm = 4.95 mm.

Correct me if i am wrong.
Thank you 

Best Regards,
Suman
