### ISSUE TITLE
Mission Planning with relative altitude

### ISSUE THREAD

**Issue by fpvcuritiba** [DroidPlanner/Tower#133]
Implement relative mission planning, since not all users like to use only absolute altitude.

As fpvcuritiba said:

> When using waypoint generator function it will create waypoints with absolute altitude, leading to a mission failure if you are not at sea level.
> 
> This issue can be reproduced using DroidPlanner to generate and upload mission to APM and then reading these waypoints with Mission Planner. At Mission Planner, in Flight Plan screen, ensure that the "Absolute Alt" is unchecked, after it just load the mission from APM that you've uploaded through DroidPlanner. You will note that "Absolute Alt" become checked.

**Comment by ayoubzar** [comment]
Hi all 
I am using Xplane with STIL .
I build my mission in MP (it seems right to me ) but when I armed an d I start the mission the flight doesn't want to take off and mission planner warn me that the altitude is zero or negative one .
I choose Relative and terrain .
My radius is 20 and the loiter like 10 and my default altitude 1000 m .
What would be the problem please ?
