### ISSUE TITLE
Feature request, RSSI monitor

### ISSUE THREAD

**Issue by Jonny360** [DroidPlanner/Tower#1330]
I have my pixhawk monitoring RSSI and I believe this is being sent through mavlink because I can see it on my OSD. Would it be possible to have droidplanner display RSSI as well? It would be very helpful for times i'm not using my video link.

**Comment by Jonny360** [comment]
Interesting @ne0fhyk My signal info only shows empty  "-" dashes for everything. My RSSI shows up on my osd, any idea why droidplanner wouldn't be displaying it?

**Comment by ne0fhyk** [comment]
@Jonny360 does it also show empty dashes for the signal strength, and battery info. How is droidplanner connected to your vehicle?

**Comment by Jonny360** [comment]
Everything under the signal shows a dash. Battery shows my voltage. Everything else seems to be working well. I get my gps position, mode, arm disarm, I can transfer flight plans. My telemetry is transmitted over openlrs. Droidplanner is connected to my radio module using a usb serial adapter and otg cable.
