### ISSUE TITLE
Restrict available flight modes when using the app for takeoff

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/Tower#1347]
* When taking off using the app, pop up a dialog asking the user whether to restrict the flight modes available (i.e: remove stab, acro... since the vehicle would crash with no active rc controller).
* Monitor rc input to auto detect whether the rc controller is active.

**Comment by phmagic** [comment]
Why ask? Why not do it automatically? When the user taps on the flight modes, then pop up a confirmation message.

**Comment by ne0fhyk** [comment]
By restricting, I meant to remove them from the flight modes drop down. 
Although, if I can reliably detect that no controller is connected, which should be possible by checking the  heartbeat, then it'll be set to activate automatically.

**Comment by ne0fhyk** [comment]
replaced by issue #1431
