### ISSUE TITLE
implement return to me

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1397]
AC 3.3 will accept  do-set-home commands which should allow return-to-me to work if the GCS sends updated home positions at regular intervals.

It should also allow the user moving the home position around before take-off and that position won't be updated during arming.

Note that the altitude in the do-set-home position should be an absolute altitude.

**Comment by rmackay9** [comment]
closely related to : https://github.com/DroidPlanner/Tower/issues/1463

**Comment by ne0fhyk** [comment]
Fixed by pr #1611 && https://github.com/dronekit/dronekit-android/pull/285
