### ISSUE TITLE
Add Baidu Map

### ISSUE THREAD

**Issue by bys1123** [DroidPlanner/Tower#1399]
# Step One: Apply a key
### 1.1 Goto http://developer.baidu.com/map/index.php?title=%E9%A6%96%E9%A1%B5
![qq 20150212231246](https://cloud.githubusercontent.com/assets/4748411/6170960/273df350-b313-11e4-9ec6-e07cc731f120.jpg)
### 1.2 Click “立即注册”
![qq 20150212231518](https://cloud.githubusercontent.com/assets/4748411/6170961/27463132-b313-11e4-8008-433db4ccd679.jpg)
### 1.3 Fill the table (use gmail maybe fail)
![qq 20150212231915](https://cloud.githubusercontent.com/assets/4748411/6170965/275a0504-b313-11e4-8118-a6c96f775c45.jpg)
### 1.4 Check your mailbox
![qq 20150212232321](https://cloud.githubusercontent.com/assets/4748411/6170963/274f72e2-b313-11e4-9c9f-ea8ca8a9bda5.jpg)
### 1.5 Open the link in the mail that Baidu send to you
![qq 20150212233555](https://cloud.githubusercontent.com/assets/4748411/6170964/27528252-b313-11e4-8388-d046c6879e32.jpg)
### 1.6 Wait few seconds you'll goto this page, sometime you'll goto the page in 1.1, that's ok, wait few minutes, try click the button described in 1.1 again.
![qq 20150212234645](https://cloud.githubusercontent.com/assets/4748411/6170962/274e4ad4-b313-11e4-86d5-b1b84bba1080.jpg)

### 1.7 Go to your mailbox as 1.5.
I remembered this gonna take two or three days. Baidu will verify the information. Or maybe in next step. 
### 1.8 Create one app
![qq 20150212235523](https://cloud.githubusercontent.com/assets/4748411/6170966/276cad9e-b313-11e4-9c48-cb408e3dbc2b.jpg)

# Step Two: Replace the key in provider file
### 2.1 Our code is finish, but it's need to run some test. we'll pull it in two days.

**Comment by phmagic** [comment]
hi @bys1123 i am stuck on the mobile number verification stage after I clicked on the email link.

**Comment by bys1123** [comment]
hi @phmagic . Sorry for the late reply. 
The format is : "__(contry code)phone number__". For mobile of china, it's like (86)13810000000. In USA, I think it should be **(1)1234000000**. And the blue poptip on the right says "remove the 0 on the front of mobile number".
Sorry for the format in the picture, maybe let you thought 00 is International Code.
Try click "API控制台" on the top right corner of page 1.1, then you can back to page 1.6.

**Comment by ne0fhyk** [comment]
@bys1123 was there any updates on this issue?

**Comment by droneboost** [comment]
Hi All,

I've integrated Baidu map SDK in Tower in my own branch, here are some screen captures, I'd like to issue a pull request for code review. Is it OK?

**Source code:**
![screenshot from 2016-07-14 14_56_53](https://cloud.githubusercontent.com/assets/10015032/16830799/b1d7f562-49d3-11e6-8a26-e4a5a1cd8f38.png)

**Main view:**
![screenshot_2016-07-14-14-13-54](https://cloud.githubusercontent.com/assets/10015032/16830609/958c2a28-49d2-11e6-8f58-788e01a8dfc6.jpeg)

**Map provider selection:**
![screenshot_2016-07-14-14-14-43](https://cloud.githubusercontent.com/assets/10015032/16830674/efb038c8-49d2-11e6-89b6-8c392c591821.jpeg)

**Map preference and offline map download:**
![screenshot_2016-07-14-14-15-10](https://cloud.githubusercontent.com/assets/10015032/16830692/0818d712-49d3-11e6-9061-b05a821bb480.jpeg)
![screenshot_2016-07-14-14-17-48](https://cloud.githubusercontent.com/assets/10015032/16830700/0ed8afb4-49d3-11e6-98aa-fef91fc2ac2e.jpeg)

**Flight waypoints setting:**
![screenshot_2016-07-14-14-18-32](https://cloud.githubusercontent.com/assets/10015032/16830721/2aa6200a-49d3-11e6-86df-a91ce23fe3a7.jpeg)

**Comment by ne0fhyk** [comment]
@droneboost yes that's great! Go ahead with the pull request.

**Comment by droneboost** [comment]
@ne0fhyk, OK, I'll prepare the pull request.

**Comment by onceme** [comment]
@droneboost Hey, man, you are the one today!

**Comment by droneboost** [comment]
@ne0fhyk , I've sent the pull request https://github.com/DroidPlanner/Tower/pull/1777

would you please do the code review?

**Comment by droneboost** [comment]
oops, seems tavis failed, I'll try to fix.

**Comment by droneboost** [comment]
@ne0fhyk , new PR https://github.com/DroidPlanner/Tower/pull/1778

**Comment by droneboost** [comment]
@ne0fhyk,
Shall we close this issue?

**Comment by ne0fhyk** [comment]
@droneboost yes, let's close it.
