### ISSUE TITLE
Prompt user to change GPS accuracy to high when using follow me

### ISSUE THREAD

**Issue by phmagic** [DroidPlanner/Tower#1424]
http://stackoverflow.com/questions/25175517/change-location-mode-to-high-accuracy-programmatically-android

**Comment by ne0fhyk** [comment]
It'll be easier to do so once google play services 7 rolls out:
http://android-developers.blogspot.com/2015/03/google-play-services-70-places-everyone.html?m=1

--
Fredia Huya-Kouadio
Senior Android Engineer, 3D Robotics
fredia@3dr.com

**Comment by ne0fhyk** [comment]
Fixed by PR #1467

**Comment by azharuddinsayed** [comment]
i want to do the same thing in xamarin forms 
so can you please let me know how i can do it.
