### ISSUE TITLE
Add Gimbal Control on GUI during Autonomous Flight

### ISSUE THREAD

**Issue by idleup** [DroidPlanner/Tower#1429]
I would like to control the Gimble from the Flight Data screen while the vehicle is flying an autonomous mission without effecting the autonomous mission.

**Comment by PaulHam211** [comment]
This would be great in conjunction with HD video downlink - https://github.com/DroidPlanner/Tower/issues/1391

**Comment by ne0fhyk** [comment]
Supported with a Solo quadcopter in version 3.2.0
