### ISSUE TITLE
Add a 'Kill Switch'

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/Tower#1433]
Similar to Parrot's ar-drone/bebop emergency mode, the kill switch should allow the pilot to immediately disable (disarm) a connected copter.

**Comment by Loop-Zilla** [comment]
Second that request.

**Comment by Thalek** [comment]
Just require a double-tap or a long tap to make it harder to activate purely by accident.

**Comment by zlite** [comment]
I just dropped a BeBop from 40 feet by accidentally hitting the Emergency Mode.  Fortunately it's very robust (because it's small and light), but for anything larger we'll need a pop-up to ask if you're sure.

**Comment by Loop-Zilla** [comment]
I would love to have a hardware E-Stop implementation, maybe even something through the headphone jack (not sure how that works, but I have seen devices use the port for analog sensing).

**Comment by BitMapping** [comment]
Somewhere Rob suggested a slider. It is more secure compared to most other inputs.

**Comment by ne0fhyk** [comment]
Fixed by PR #1470

**Comment by ne0fhyk** [comment]
Disabling the feature until AC 3.3 is released since it adds support for `disarm` while in flight.

**Comment by ne0fhyk** [comment]
For versions prior to AC 3.3, starting accelerometer calibration could be used as a kill-switch, since it'll cause the autopilot to block until calibration is complete.

More of a hack though!

**Comment by squilter** [comment]
For versions before 3.3, the kill switch will change the mode to `stabilize` and then disarm.
For 3.3+, the kill switch will send the disarm packet with the the force flag (#1494).

**Comment by squilter** [comment]
@ne0fhyk How is the arducopter version checker going?

**Comment by ne0fhyk** [comment]
Fixed by #1511

**Comment by MaxQu** [comment]
Support the emergency disarm. Will save blade when the drone tips over.
