### ISSUE TITLE
survey and trigger

### ISSUE THREAD

**Issue by arnaudstephan** [DroidPlanner/Tower#1440]
Hello, new here. from France.

In survey mode i don't understand the triggering method used : is it a do digicam control (triggering when passing trough GPS coordinates) or a distance trigger ? Is it possible to ad an option for that ? Thank you.

**Comment by BitMapping** [comment]
CAM_TRIGG_DIST is what is set. You find the corresponding "CAM" entries in the log file - if logging is enabled. You have to set an appropriate WP_NAV_SPEED value manually (unfortunately).
