### ISSUE TITLE
problem with flight time

### ISSUE THREAD

**Issue by arnaudstephan** [DroidPlanner/Tower#1441]
Flight time don't change when modifing the speed by adding a change speed point in a mission.

Other question : what is the speed of a survey ?

Thanks

**Comment by ne0fhyk** [comment]
the speed of a survey is the speed defined by the [`WPNAV_SPEED`](http://copter.ardupilot.com/wiki/configuration/arducopter-parameters/#waypoint_horizontal_speed_target_wpnav_speed) parameter. However, if you add a change speed point in a mission before the survey, then the speed will be temporarily set by that point.

**Comment by arnaudstephan** [comment]
Thank you. And what about the wrong flight time calculation ?

**Comment by ne0fhyk** [comment]
That's an issue indeed. Right now the time calculation is estimated based on the WPNAV_SPEED parameter only. 
That needs to be fixed to account for any change speed point inside the mission.

**Comment by ne0fhyk** [comment]
Fixed by pr #1815
