### ISSUE TITLE
UDP Connection bug

### ISSUE THREAD

**Issue by ivanma72** [DroidPlanner/Tower#1453]
How to replicate this issue:
1. Change connection setting to UDP
2. Press "Connect" button
3. Press "Connect" again. Telemetry bar icons and flight notification in notification area will show up

It seems that an AttributeEvent.STATE_CONNECTED event is incorrectly broadcasted the second time, which causes the telemetry bar to be shown, etc.

**Comment by ne0fhyk** [comment]
Fixed by PR https://github.com/DroidPlanner/DroneKit-Android/pull/121
