### ISSUE TITLE
Cant open saved wp files (dpwp)

### ISSUE THREAD

**Issue by sditges** [DroidPlanner/Tower#1457]
Hi, since latest update off tower, cant open earlyer saved mission - dpwp files " Error while opening"
Thats verry bad!
Is there a solution?

**Comment by squilter** [comment]
I am not able to reproduce the problem.  Does this happen with all dpwp files, or just one particular file?

**Comment by squilter** [comment]
Nevermind, I understand what caused the issue now.  The easiest way to fix this is probably for us to stop using dpwp files and save all missions as txt files.  #1482.  Unfortunately, some info gets lost when exporting to txt.

**Comment by squilter** [comment]
Eventually missions will all get imported as txt files that are compatible with mission planner.
