### ISSUE TITLE
Add support for UDP client connection

### ISSUE THREAD

**Issue by orlando3d** [DroidPlanner/Tower#1458]
We are testing a new Wifi modules configured as a UDP server with UART connected to the autopilot telemetry port and being able to establish a mavlink connection to Tablet/PC. 

We have tested successfully in Tower using the UDP option but every time we need to start the connection we need to open first another UDP app ( TermUDP )  in the tablet to specify the Server IP and Port and finally send any character to the Wifi module( I guess this way we let the UDP server know the tablet IP ) and then successfully start sending data from the Autopilot.

That option is available in Mission Planner as UDPCl option were the server IP along the PORT is required to start the data flow. 

Is there any option in Tower to setup the UDP as a client ? or plan to be added ?.

Thanks

**Comment by ne0fhyk** [comment]
Fixed by PR #1471 and PR https://github.com/DroidPlanner/DroneKit-Android/pull/122
