### ISSUE TITLE
Request: dragging coincident points chooses most recent one

### ISSUE THREAD

**Issue by chapman** [DroidPlanner/Tower#1462]
There's a really frustrating workflow if you drop a new waypoint over the top of an existing one (which seems too easy to do, perhaps a preference for this spacing threshold?)

- drop new waypoint over the top of another
- hold+drag drags the old one, which you don't want to move, but you have to move that away
- then you can hold+drag on the new one, move it where it should be
- go back to reset the position of the older one

This would be alleviated if the newest waypoint is on 'top' and will take precedence in a coincident point situation

**Comment by squilter** [comment]
I think this is related to both #1079 and #952.  Ultimately, we concluded there was no proper fix for either.

**Comment by ne0fhyk** [comment]
@chapman as @squilter pointed out, we're working within the limitations of the google map api, and there's no proper fix for the issue you encountered.
