### ISSUE TITLE
When using auto-pan; zoomlevel gets wrong; Zoombuttons missing.

### ISSUE THREAD

**Issue by GeVaSta** [DroidPlanner/Tower#1464]
When you use the autopan feauture (touch and hold the location icon), after a disconnect or perhaps even GPS loss, the zoomlevel changes to displaying the whole world.
It is then very difiicult to zoom in onl by pinching a lot off time. 
A zoom + and - button would be preferable too.

**Comment by ne0fhyk** [comment]
Thanks for the feedback, but there's no plan to add zoom buttons, as they would clutter the ui.

**Comment by GeVaSta** [comment]
Have you already fixed te spontaneous zoom-out? Because you closed this case I suppose you did. Or did you misunderstand my issue?
Solving the zoom-out on disconnect issue, makes the need for zoombutton less important.

**Comment by ne0fhyk** [comment]
I'm not able to reproduce the zoom out issue you're mentioning. The map
view should stay on the same zoom level when the user disconnects, or when
the link between the GCS and vehicle breaks.

--
Fredia Huya-Kouadio
Senior Android Engineer, 3D Robotics
fredia@3dr.com

**Comment by sditges** [comment]
i have the same trouble with zoomout

**Comment by GeVaSta** [comment]
I'll try to find out when exactly it is happening and report back.
