### ISSUE TITLE
Voltage not correctly displayed for 8S pack

### ISSUE THREAD

**Issue by zill539** [DroidPlanner/Tower#1466]
Hi,
I find when i attach my fully charged 8s pack it is displayed at -32.5v. (should be 33.6v) All works fine in mission planner. As the voltage drops below 32.5v the display then works correctly. Im not sure if there is a limitation within the code or its something else.

**Comment by ne0fhyk** [comment]
Being fixed through https://github.com/ne0fhyk/mavlink/issues/1 and https://github.com/ne0fhyk/mavlink/issues/3

**Comment by ne0fhyk** [comment]
Fixed in [3DR Services v1.2.20](https://github.com/DroidPlanner/DroneKit-Android/releases/tag/3DRServices-v1.2.20).
