### ISSUE TITLE
Add option to change default height / altitude

### ISSUE THREAD

**Issue by gmaclennan** [DroidPlanner/Tower#1486]
Tower currently defaults every waypoint to 20m. I cannot find any way to change that other than changing each waypoint manually. Would be great to be able to change the default height for new waypoints. We fly in rainforest regions where 20m would not clear the trees and one mistake would result in a dead drone :-(

**Comment by ne0fhyk** [comment]
@gmaclennan you can either set a `takeoff` waypoint, and specify the takeoff altitude which will cause the waypoints added afterward to use it as their base altitude.
Alternatively, you can also select all the waypoints you'd like to update via the `selector` tool, and open the right side detail panel to edit all the selected waypoints in bulk.

![editor_select_tool_screenshot](https://cloud.githubusercontent.com/assets/914968/7762031/f8e405a4-ffe2-11e4-85ce-4b3e883afa7e.png)
![editor_waypoint_selected_screenshot](https://cloud.githubusercontent.com/assets/914968/7762032/f8e89042-ffe2-11e4-9859-69a2e658a9f5.png)

**Comment by gmaclennan** [comment]
Thanks @ne0fhyk this is very helpful.

It would still be useful to define a default though, since the current default is kind of arbitrary, and changing the height every time is an additional step for users.
