### ISSUE TITLE
Force disarm of copter by sending DISARM command with param2 with 21196

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1494]
AC3.2.1 and AC3.3 require the vehicle to be landed before the vehicle will accept a disarm request.
AC3.3 will accept the disarm however (regardless of whether the vehicle is landed or not) if param 2 is set to 21196

**Comment by hamishwillee** [comment]
... as documented in [MAV_CMD_COMPONENT_ARM_DISARM](http://copter.ardupilot.com/wiki/common-planning-a-mission-with-waypoints-and-events/common-mavlink-mission-command-messages-mav_cmd/#copter-2)

**Comment by squilter** [comment]
With the addition of DroidPlanner/DroneKit-Android#172, this is easy to implement.  We just need to find a good place to put the button.

**Comment by ne0fhyk** [comment]
This is already implemented:
https://github.com/DroidPlanner/Tower/issues/1433

The implementation needs to be updated to make use of the new capability.

--
Fredia Huya-Kouadio
Android Tech Lead, 3D Robotics
fredia@3dr.com

**Comment by squilter** [comment]
I will implement this shortly.  See issue #1433
