### ISSUE TITLE
"400ft exceeded" warnings with Plane (altitude AMSL)

### ISSUE THREAD

**Issue by github-0** [DroidPlanner/Tower#1497]
Hi,

Tried Tower for the first time today with Pixhawk/Plane 3.3.0. Tower seems to display the Above Mean Sea Level altitude instead of home altitude and in my case this triggers a loop of 400ft exceeded warnings. I did disable the warning, but it is higly inconvenient that the HUD shows AMSL instead of AGL. Any chance to get this changed or show both?

**Comment by ne0fhyk** [comment]
@github-0 thanks for the feedback. ArduPlane behaves differently from ArduCopter by reporting the AMSL instead of AGL, and Tower just forward that information along.

**Comment by github-0** [comment]
From what I can understand, this same issue was solved in Mission Planner here https://github.com/diydrones/MissionPlanner/issues/40 (also https://github.com/diydrones/ardupilot/issues/417). They changed the HUD field to GLOBAL_POSITION_INT.relative_alt field so that the behavior is consistent between copter and plane.

**Comment by ne0fhyk** [comment]
@github-0 thanks for the info. The issue is being fixed through #1517, and the next beta release will incorporate the fix.
