### ISSUE TITLE
feature request: Take me to my vehicle

### ISSUE THREAD

**Issue by geofrancis** [DroidPlanner/Tower#1499]
if an aircraft goes down it would be nice to have a button that brings up an arrow and distance to the aircraft either the current location or the last known location allowing you to track it down relatively easily by just following the arrow. a bit like the home arrow and distance on an osd but pointing to the aircraft.

**Comment by ne0fhyk** [comment]
@geofrancis This is already provided by the `Locator` section. That section allows you to load the telemetry log (`tlog` files) for completed flights allowing you to retrace the path of the vehicle.
That section could benefit from an improved UX, but that should be another issue.
