### ISSUE TITLE
Mobius Action Camera Lens C

### ISSUE THREAD

**Issue by sbcrumb** [DroidPlanner/Tower#1509]
Can anyone help me with the Specs for this Camera? And can we get it added to Tower?

<cameraInfo>
  Name=Mobius Lens C Name>
  SensorWidth>?? SensorWidth>
  SensorHeight>?? SensorHeight>
  SensorResolution>?? SensorResolution>
  FocalLength>?? FocalLength>
cameraInfo>

**Comment by FLYBYME** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<cameraInfo>
    <Name>Mobius A lens</Name>
    <SensorWidth>5.07</SensorWidth>
    <SensorHeight>3.38</SensorHeight>
    <SensorResolution>5</SensorResolution>
    <FocalLength>??</FocalLength>
</cameraInfo>
```

I dont know what the focal length would be..

**Comment by sbcrumb** [comment]
Is this the specs for the C version lend?

**Comment by FLYBYME** [comment]
I believe the sensor is the same.

**Comment by ne0fhyk** [comment]
@sbcrumb @FLYBYME are these specs complete?
