### ISSUE TITLE
Can't set DO_JUMP to -1

### ISSUE THREAD

**Issue by Hasi123** [DroidPlanner/Tower#1516]
Currently there is no way to set the DO_JUMP to -1, so the mission is repeated indefinitely.

**Comment by TShapinsky** [comment]
@Hasi123 were regular DO_JUMP command working because until recently DO_JUMP was not supported by ardupilot

**Comment by ne0fhyk** [comment]
According to Randy, do jump is only supported as part of a mission.

--
Fredia Huya-Kouadio
Android Tech Lead, 3D Robotics
fredia@3dr.com

**Comment by ne0fhyk** [comment]
Fixed by pr #1593
