### ISSUE TITLE
Erratic behaviour when other Mavlink systems are sending hearbeats on the same link

### ISSUE THREAD

**Issue by walmis** [DroidPlanner/Tower#1523]
When connecting to a drone (APM:Copter 3.3) which features MAVLink routing, mavlink heartbeats and other packets from other systems are forwarded to DroidPlanner. In my case there are heartbeats from APM:Copter, Storm32 gimbal and Radio controller. When DroidPlanner receives heartbeat messages from different systems it switches modes, changes buttons, and constantly notifies - gps 3d lock, gps lost, gps 3d lock, gps lost and so on. It then becomes unusable.
A simple fix would be to filter out non-autopilot systems based from HEARTBEAT.autopilot messages.

**Comment by ne0fhyk** [comment]
@walmis this is a duplicate for https://github.com/DroidPlanner/DroneKit-Android/issues/124
Could you report there instead. 
thanks!
