### ISSUE TITLE
After resuming paused auto-mission ROI is lost

### ISSUE THREAD

**Issue by TShapinsky** [DroidPlanner/Tower#1524]
there is a command `MAV_CMD_OVERRIDE_GOTO` that would tell the copter to maintain current position, the problem is that it isn't implemented by anything.

**Comment by squilter** [comment]
It's not implemented in ArduCopter as far as I can tell.  But supposedly mission planner has the ability to pause a mission ("supposedly"), so let's try looking into how that was implemented.

**Comment by hamishwillee** [comment]
Probably not helpful - but I *think*if  you switch out of auto the mission is paused and the copter loiters. There is a parameter that you can set to determine whether the mission restarts from where it left off or the beginning again.

**Comment by ne0fhyk** [comment]
Closing until support is added from the autopilot.
