### ISSUE TITLE
AC3.3 real-time vibration view

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1551]
![mp_vibedisplay_full](https://cloud.githubusercontent.com/assets/1498098/8971403/fe6d8228-368a-11e5-8617-291bba01633f.png)

corresponding mission planner issue: https://github.com/diydrones/MissionPlanner/issues/948

**Comment by rmackay9** [comment]
This is the other item that I think is really critical for the Copter-3.3 release that should go out within about 3 weeks.

I know you guys are busy but just want to highlight the importance of these two items.
https://github.com/DroidPlanner/Tower/issues/1552

**Comment by ne0fhyk** [comment]
Fixed by pr #1600

**Comment by rmackay9** [comment]
great, thanks!!
