### ISSUE TITLE
AC3.3: real-time EKF view

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1552]
![mp_ekf_full](https://cloud.githubusercontent.com/assets/1498098/8971408/1078180c-368b-11e5-8619-b33bfba29da5.png)

corresponding mission planner issue: https://github.com/diydrones/MissionPlanner/issues/949

**Comment by rmackay9** [comment]
With AC3.3-rc9 out now in testing, we're quite close to the final Copter-3.3 release.  I think this item and the vibration viewer are really important for that release because it will warn pilots before EKF or vibration issues get bad enough to cause a crash.

**Comment by ne0fhyk** [comment]
Fixed by pr #1583.
@rmackay9 This should be part of the beta 3 release coming out tomorrow.
