### ISSUE TITLE
Tower crashes when creating a structure scanner waypoint

### ISSUE THREAD

**Issue by franknitty69** [DroidPlanner/Tower#1560]
Go to editor
select waypoint>survey
click anywhere on the map
tower crashes with a message "Unfortunately, Tower has stopped".

this happens 100% of the time. i have tried rebooting and a re-installation of Tower.

Tower: v3.1.6
3DR Services: v1.3.2
Device: Samsung Galaxy Tab S 8.4

**Comment by ne0fhyk** [comment]
@franknitty69 the issue has been identified and fixed, and will be out in a beta release for `3DR Services v1.3.3` later today.

**Comment by ne0fhyk** [comment]
Fixed by commit https://github.com/dronekit/dronekit-android/commit/2d469ce21de2514486cd5a686bdec578b36be2da
