### ISSUE TITLE
Avoiding user incorrect settings on Land

### ISSUE THREAD

**Issue by lvale** [DroidPlanner/Tower#1561]
GCS should try to prevent users from setting invalid locations for Land.

Ref: https://github.com/diydrones/ardupilot/commit/c87929e907d17d6f1a7dd5d753d6b84f29e7d9c5

**Comment by ne0fhyk** [comment]
@lvale I don't think the linked issue is possible from Tower since there's no option to edit the `land` waypoint in the editor screen.

**Comment by lvale** [comment]
This issue arose from a flight that I've sent the log to Grant, and has been discussed with Tridge. I'm just submitting to all GCS for consistency sake. (note the issue in on Plane)
