### ISSUE TITLE
n ft. Exceeded instead of 400ft. Exceeded

### ISSUE THREAD

**Issue by ThorstenDP** [DroidPlanner/Tower#1564]
Hi all,
In Germany (Europe?) the maximum altitude a.g.l. is 100m which is 328ft.
Since this is a fixed value it is pretty useless over here. It would be great if the altitude level could be user defined and in addition to the US units in SI units as well.
Best regards,
Thorsten

**Comment by ne0fhyk** [comment]
Fixed by pr #1570

**Comment by ThorstenDP** [comment]
Prefect! Thanks!
