### ISSUE TITLE
3DR Radiolink not showing values for the parameters in drop down list

### ISSUE THREAD

**Issue by GeVaSta** [DroidPlanner/Tower#1571]
When you click the Radiolink Signalstrength at the top of the screen the item names are present (like RSSI) but no values are displayed. All parameters show "--".
Radio link loss is reported okay by voice feedback.
This was also happening in the previous version and now in version v3.2.0.beta1.

The radio is connected using USB OTG-cable.

**Comment by ne0fhyk** [comment]
@GeVaSta that issue has been fixed, and will be available in the next beta release!

**Comment by GeVaSta** [comment]
Perfect. Thanks.
