### ISSUE TITLE
Exceed altitude warning very fast

### ISSUE THREAD

**Issue by cala2** [DroidPlanner/Tower#1577]
I found in stable release  but I suppose is the same in beta, exceed altitude warning was checked and when I exceed that altitude the speech is so quick that can't finish the phrase and repeat continuously like a crazy woman. (Sorry if solved in beta I'm in winter and few oportunities to fly to try again in beta,  soon)

**Comment by squilter** [comment]
I saw this issue the other day when flying plane.  I thought it was plane-related, but I guess not.

**Comment by ne0fhyk** [comment]
Fixed by pr #1596
