### ISSUE TITLE
Easy access to tuning parameter

### ISSUE THREAD

**Issue by Jimmydaux** [DroidPlanner/Tower#1580]
It would be really convenient to have easy access to tuning parameters either with a UI screen for tuning or with a shortened list of parameters related to flight tuning.  This could be as simple as allowing the user to create a list of favorite parameters that would allow them to customize the parameters that would be available for display. A real time tuning screen would be nice as well but would obviously be a lot more work. I'd love to have easy access to sliders/up down arrows to tune PIDS for each axis. It never hurts to ask :)

**Comment by ne0fhyk** [comment]
@Jimmydaux thanks for the feedback. This is already on the roadmap, but it might take some time because of the level of effort required.
I'm closing this issue for now.
