### ISSUE TITLE
Attempting to change NAVL1_PERIOD results in crash

### ISSUE THREAD

**Issue by bveenker** [DroidPlanner/Tower#1582]
Seen on two android devices: trying to change the value for this parameter results in a crash.

Any other parameter I try to change works as expected, but the moment I start typing on NAVL1_PERIOD I get an "Unfortunately Tower Has stopped" box

ETA: I also see this crash when changing NAVL1_DAMPING

ETA: I've tried every MAVLink app in the store, they all do this. The only exception is AndroPilot, it works fine

**Comment by ne0fhyk** [comment]
@bveenker which version of Tower and 3DR Services are you running?

**Comment by bveenker** [comment]
3DR services v1.3.3
Tower v3.1.6

**Comment by ne0fhyk** [comment]
Fix by commit 0e097f08ee3bc2d4ff10fce5f2aca1546398733b
