### ISSUE TITLE
Ensure Copter-3.3 GPS status 4 is processed

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1588]
recent ardupilot versions including Copter-3.3-rc10 will report a GPS status of "4" when they have both 3D fix + SBAS.  Tower may currently be crying out "No GPS Lock" when it sees this previously unused status.

**Comment by ne0fhyk** [comment]
Implemented by https://github.com/dronekit/dronekit-android/pull/230 and https://github.com/DroidPlanner/Tower/pull/1557
