### ISSUE TITLE
Tower crashes when switching Map Tile Provider

### ISSUE THREAD

**Issue by franknitty69** [DroidPlanner/Tower#1589]
**steps to reproduce**
-go to settings>user interface>map provider preferences
-press Map Tile Provider, in the modal window, select the Mapbox radio button
-after a few seconds, tower crashes with notification that says "Unfortunately, Tower has stopped". The notification has Report or OK buttons.
-press ok to dismiss the notification and tower is restarted back in map provider preferences

**expected result**
the map provider preferences is changed to mapbox and mapbox preferences are enabled

Tower Version: v3.2.0.beta.3
3DR Services Version: v1.3.4.beta.0
Device: Samsung Galaxy Tab S 8.4 (Lollipop)

**Comment by ne0fhyk** [comment]
Which version of the tower app are you seeing the crash on?

--
Fredia Huya-Kouadio
Android Tech Lead, 3D Robotics
fredia@3dr.com

**Comment by franknitty69** [comment]
Tower: v3.2.0.beta.3
3DR Services: v1.3.4

On Wed, Sep 9, 2015 at 12:55 PM, Fredia Huya-Kouadio <
notifications@github.com> wrote:

> Which version of the tower app are you seeing the crash on?
>
> --
> Fredia Huya-Kouadio
> Android Tech Lead, 3D Robotics
> fredia@3dr.com
> On Sep 8, 2015 5:16 PM, "Ahmed Agbabiaka" <notifications@github.com>
> wrote:
>
> > [B]steps to reproduce[/B]
> > -go to settings>user interface>map provider preferences
> > -press Map Tile Provider, in the modal window, select the Mapbox radio
> > button
> > -after a few seconds, tower crashes with notification that says
> > "Unfortunately, Tower has stopped". The notification has Report or OK
> > buttons.
> > -press ok to dismiss the notification and tower is restarted back in map
> > provider preferences
> >
> > [B]expected result[/B]
> > the map provider preferences is changed to mapbox and mapbox preferences
> > are enabled
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DroidPlanner/Tower/issues/1589>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DroidPlanner/Tower/issues/1589#issuecomment-138973467>
> .
>



-- 
Ahmed Agbabiaka
Accenture Federal Services | Manager
9811 Berrywood Court Springdale, MD 20774
Mobile: 202.340.8854

**Comment by guiseco** [comment]
09-11 10:38:06.181 23281 23281 E AndroidRuntime: FATAL EXCEPTION: main

09-11 10:38:06.181 23281 23281 E AndroidRuntime: Process: org.droidplanner.android, PID: 23281

09-11 10:38:06.181 23281 23281 E AndroidRuntime: java.lang.IllegalStateException: Parent activity must implement org.droidplanner.android.dialogs.EditInputDialog$Listener

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at org.droidplanner.android.dialogs.EditInputDialog.onAttach(EditInputDialog.java:68)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:853)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:833)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5253)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)

09-11 10:38:06.181 23281 23281 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

09-11 10:38:06.181   533  1204 W ActivityManager:   Force finishing activity org.droidplanner.android/.activities.helpers.MapPreferencesActivity

**Comment by ne0fhyk** [comment]
Fixed by pr #1596
