### ISSUE TITLE
Parallel 3G/4G web access doesn't work when connected to Solo 

### ISSUE THREAD

**Issue by mtbsteve** [DroidPlanner/Tower#1603]
The parallel access to the web via 3G for map download when connected to Solo via wifi doesn't work. 
Its working fine with the Solo app by the way.

**Comment by ne0fhyk** [comment]
@mtbsteve we just added support for that on the solo app, and it'll eventually be done on Tower as well.

**Comment by ne0fhyk** [comment]
Fixed by pr #1612
