### ISSUE TITLE
Resume control with Solo controller not possible 

### ISSUE THREAD

**Issue by mtbsteve** [DroidPlanner/Tower#1604]
Once you put Solo into guided mode by any of the Tower commands the only way to regain control via the Solo controller is to switch to Loiter in Tower. More consistent would be to be able to use the Fly button on the Solo controller to exit any auto fight modes

**Comment by ne0fhyk** [comment]
@mtbsteve pressing the `fly` button on the controller always bring you back to `loiter` mode not matter which app changed it.

**Comment by mtbsteve** [comment]
@ne0fhyk sorry no, could you please check again. 
Pressing Fly puts Solo into Land. There is no way to get back frim Guided  into Loiter except setting it in Tower. 
It's 100% reproducible with Solo FW 1.1.5 and Tower beta3.

**Comment by TShapinsky** [comment]
@mtbsteve Tower shouldn't be interfering with the communication between the controller and solo. Does it still go into land if you don't have Tower connected?

**Comment by mtbsteve** [comment]
Ok, here's a step by step instruction how to reproduce it:
1. power Solo controller and Solo 
2. connect Android device to Solo wifi, launch Tower 
3. wait until Solo got GPS fix
4. In tower, press connect, then arm
5. press takeoff in Tower
6. Solo is in Guided mode, hovering 
7. now press Fly in the Solo controller  shortly- nothing happens. Press Fly for a few seconds- Solo goes into Land mode. 
The only way to get back in Loiter is to set it in the Tower menu.
It's not a showstopper, but annoying and not what you expect.

**Comment by TShapinsky** [comment]
@mtbsteve I understand but what I'm trying to clear up is whether it's a problem with tower or with your solo firmware. Because tower isn't responsible for handling the button presses on the controller it is likely that you have a problem with your firmware (probably just a parameter) not with Tower. So if you were to takeoff with tower and then disconnect tower before hitting the fly button would it still go into land. Also, if you setup the A and B buttons in the solo app can you switch without having to use tower or is it permanently stuck in land until you use tower?

**Comment by mtbsteve** [comment]
@TShapinsky @Ne0fyhk I can't say if it is a bug in Tower or the Solo firmware. I tested today again and can say that it only happens in Guided mode in Tower. When I fly an Auto mission I can always press Break or hit Fly to bring it back to Loiter. So with all Solo flight modes initiated in the Solo app. 

Today Tower even crashed when I hit the Solo Break button while being in Guided mode. The Solo was fortunately stable hovering  above me until Tower restarted and I could switch to Loiter to regain control. 
This is becoming a safety issue.  Please reopen this and have a look at it. Thanks.

**Comment by ne0fhyk** [comment]
@mtbsteve while on the ground, it seems the controller is not able to switch away from any modes when pressing the fly button. However it is able to do so when the vehicle is airborne.

I tried to reproduce your issue but was unable to do so. If I take off in guided using tower, or if I switch to guided mode in the air using tower, I'm always able to go back to loiter by pressing the fly button on the controller.

**Comment by ne0fhyk** [comment]
@mtbsteve if it doesn't work in your case, that may signal an issue with your controller.
You can test this by mapping another mode (i.e: fly manual) to the `a` or `b` button, switching to the mapped mode while in flight, and attempt to switch back to loiter using the fly button.

**Comment by mtbsteve** [comment]
@fredia Amazingly it works now with Solo firmware 1.2.

On Sep 23, 2015 8:05 PM, "Fredia Huya-Kouadio" <notifications@github.com>
wrote:
>
> @mtbsteve if it doesn't work in your case, that may signal an issue with
your controller.
> You can test this by mapping another mode (i.e: fly manual) to the a or b
button, switching to the mapped mode while in flight, and attempt to switch
back to loiter using the fly button.

**Comment by ne0fhyk** [comment]
@mtbsteve great to hear!
