### ISSUE TITLE
support for on-board compass calibrator

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1623]
Copter-3.4 will include the new on-board compass calibrator from the solo guys.  It will also be in the 3.4.0 plane release which will go out long before the Copter-3.4 release.

Protocol is here:
https://github.com/diydrones/ardupilot/blob/master/libraries/GCS_MAVLink/message_definitions/ardupilotmega.xml#L713

MAVProxy implementation is here: https://github.com/DroneCode/MAVProxy/blob/master/MAVProxy/modules/mavproxy_calibration.py#L115

The new calibration also does scaling (aka soft-iron corrections) which can be very worthwhile on some aircraft.

Here's the equivalent Mission Planner issue: https://github.com/diydrones/MissionPlanner/issues/990

**Comment by Linjieqiang** [comment]
when is the copter 3.40 realese?I am looking forward to it.

**Comment by rmackay9** [comment]
@Linjieqiang, Copter-3.4 is many months away I'm afraid.  Copter-3.3 is just on it's way out now.

**Comment by ne0fhyk** [comment]
Added in pr #1782
