### ISSUE TITLE
Log file missing

### ISSUE THREAD

**Issue by ThorstenDP** [DroidPlanner/Tower#1626]
Hi all,
I checked all settings and search all reasonable folders (at least I hope so), but I cannot find any log files on my tablet. Had there been some changes? Not sure if relevant but I am using xBee S1 pro telemetry.
Thanks and best regards,
Thorsten

**Comment by ne0fhyk** [comment]
@ThorstenDP all the tlogs files are stored by 3DR Services under the `/sdcard/Android/data/org.droidplanner.services.android/files/tlogs` directory. In that directory, they're partitioned by front-end apps (i.e: `org.droidplanner.android` for Tower...)

**Comment by ThorstenDP** [comment]
Great! Thanks a lot! I must have overlooked it...
