### ISSUE TITLE
Waypoint reordering buggy

### ISSUE THREAD

**Issue by robcee** [DroidPlanner/Tower#1631]
STR:

1. Enter Flight Editor
2. Draw a sequence of waypoints
3. Add a new waypoint, change it to a Region of Interest
4. Hold and Drag new waypoint through the list to position 1.

Expected:
ROI gets set to number 1.

Actual:
Bumping the edge of the screen stops reordering waypoint and breaks the original flight plan. Some waypoints become transparent in the list at the bottom and funny interaction ensues.

Alternate fix to drag and drop: Be able to set the waypoint number manually on the waypoint editor itself. Would make the algorithm for reordering waypoints simpler to deal with if it's not being updated dynamically as a result of a faulty drag and drop operation.

**Comment by robcee** [comment]
![screenshot_2015-10-05-13-04-27](https://cloud.githubusercontent.com/assets/27976/10287591/f1cf66b0-6b61-11e5-9112-360c1c488612.png)

Screenshot showing mangled flightpath and transparent waypoints in the list area at bottom. Might take a couple of drag attempts for things to get confused. I added an ROI as above then another waypoint with a change of speed order.

**Comment by ne0fhyk** [comment]
Fixed by pr #1793
