### ISSUE TITLE
Change Speed Mission item values too coarse

### ISSUE THREAD

**Issue by robcee** [DroidPlanner/Tower#1633]
STR:

1. In Flight Editor, Create a new Waypoint
2. Set Speed to 1.0m/s
3. Click on 1.0 value to bring up the text editor
4. Enter 0.5m/s

Expected:
Be able to set half m/s values.

Actual:
Unable to enter decimals.

Suggestion:
Remove the editor and add half m/s values to the slider. WPNAV_SPEED supports increments of 50cm/s.

**Comment by ne0fhyk** [comment]
Fixed by pr #1650
