### ISSUE TITLE
add Read only mode

### ISSUE THREAD

**Issue by petrbartak** [DroidPlanner/Tower#1634]
I would like to ask you to add a "read only" mode in future releases. I some cases it would be great and safe to use such a mode. I would prefer to use such a mode in case of two men operation, one fully trained pilot and one camera and ground station operator only. 

Best regard,
Petr Bartak

**Comment by ne0fhyk** [comment]
@petrbartak Thanks for the request, but this is not a feature we're planning to implement at this point in time.
