### ISSUE TITLE
How to setup offline maps?

### ISSUE THREAD

**Issue by smocksam** [DroidPlanner/Tower#1636]
I need more of an explanation as far as how to set this up.

I'm not exactly sure what to paste in for the api section.  

I thought I had it.

It says it's saving maps, but I'm not sure how to test. I guess turning my connection off would probably do it.

The map it shows me is just a road map.  I must have done something wrong since I don't have the satellite maps.

Thanks

**Comment by busyStone** [comment]
#1502

**Comment by ne0fhyk** [comment]
<img width="1552" alt="screen shot 2015-10-11 at 6 30 48 pm" src="https://cloud.githubusercontent.com/assets/914968/10420676/f3c751b2-704d-11e5-94a2-88e782d7ec8c.png">
<img width="1552" alt="screen shot 2015-10-11 at 6 32 22 pm" src="https://cloud.githubusercontent.com/assets/914968/10420677/f3ca6ab4-704d-11e5-85c4-e6551dfc2323.png">
<img width="1552" alt="screen shot 2015-10-11 at 6 49 31 pm" src="https://cloud.githubusercontent.com/assets/914968/10420678/f3cca73e-704d-11e5-8394-50ffd9eebfbe.png">

**Comment by ne0fhyk** [comment]
@smocksam the [offline maps wiki](https://github.com/DroidPlanner/Tower/wiki/Offline-Maps) was updated with instructions to retrieve the mapbox id and access token.
