### ISSUE TITLE
I developing preset waypoints to survey nuclear dome. Waypoints are organized with xml files. The rpogram  Microstation 

### ISSUE THREAD

**Issue by azn802** [DroidPlanner/Tower#1637]

**Comment by azn802** [comment]
Do you think it is compatible with the DroidPlanner??

**Comment by ne0fhyk** [comment]
@azn802 Sorry but we don't support xml files generated by microstation.

**Comment by azn802** [comment]
Okay. Thank you for comment. Then how waypoints saved in the DroidPlanner? Is it kind of assembly language with GPS position?
