### ISSUE TITLE
Edit text to speech

### ISSUE THREAD

**Issue by CX-Piet** [DroidPlanner/Tower#1638]
Hi, 
is it possible to edit the text for warnings? Same like in MissionPlanner? 
English terms pronounced in german sounds a bit weird...

THX

**Comment by ne0fhyk** [comment]
@CX-Piet the warnings have been externalized to allow [localization](https://developer.android.com/guide/topics/resources/localization.html). All that remains to do is to provide a german version of the warnings.

@squilter @zumbrunnen up for it?

**Comment by squilter** [comment]
Is it just about adding more strings to the german strings.xml?

**Comment by ne0fhyk** [comment]
@squilter yes, specifically adding the german equivalent for this section: https://github.com/DroidPlanner/Tower/blob/2e1e5118beddb44e9e7ebf908669e02f3ab94c45/Android/res/values/strings.xml#L529-l571

**Comment by squilter** [comment]
Sure, I'll do it later this week.

**Comment by ne0fhyk** [comment]
@squilter [sounds good](https://github.com/DroidPlanner/Tower/issues/1657).

**Comment by zumbrunnen** [comment]
@squilter if you're using Android Studio: it has a nice Translation Editor. If you need help, lass es mich wissen. :wink:

**Comment by squilter** [comment]
@zumbrunnen Thanks for the tip.  The translations editor looks pretty nice!
