### ISSUE TITLE
Survey, spline survey, and camera trigger don't trigger gopro on solo

### ISSUE THREAD

**Issue by bheiland** [DroidPlanner/Tower#1642]
Trying to photograph during Survey or Spline survey or with camera trigger and none of these modes will take images on Solo.  Tested with hero3+ BLACK and Hero4 Black.

Mission flies and completes but no images are taken.

**Comment by ne0fhyk** [comment]
@bheiland This issue is caused by the solo firmware. At the moment, it doesn't yet support handling of camera trigger.
