### ISSUE TITLE
Copter crash while in Follow-me

### ISSUE THREAD

**Issue by rmackay9** [DroidPlanner/Tower#1648]
There's a report by Stephan on the Copter-3.3 beta testing thread which looks a lot like a NaN somehow got into the position controller while he was doing Follow-me with Tower ver 3.2 and Copter-3.3.

We've seen this once before using beta testing so I added more checks around the requests received from the GCS but apparently that wasn't enough.

I wonder if someone on the Tower side could check to see if there's some way that Tower might send very bad values.  Also I'd like confirmation that Tower is using one of these:
MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED
MAVLINK_MSG_ID_SET_POSITION_TARGET_GLOBAL_INT

**Comment by ne0fhyk** [comment]
More info @ https://www.youtube.com/watch?v=sZrAzr31jkw
