### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by CX-Piet** [DroidPlanner/Tower#1658]
Using Tower-v3.2.1.beta.1 
When starting the app it shows a message to update 3DR Services. 
Same messsage by opening settings menu. 
But there is no newer version of 3DR Services (v1.4.2) available.

**Comment by ne0fhyk** [comment]
@CX-Piet That version requires the beta version for 3DR Services which you can get @ https://play.google.com/apps/testing/org.droidplanner.services.android

**Comment by CX-Piet** [comment]
Oups...searched for that but did not find it! THANKS!
