### ISSUE TITLE
Phone UI: battery, mode and HDOP values wrap to second line

### ISSUE THREAD

**Issue by ggregory8** [DroidPlanner/Tower#1663]
I'm running a OnePlus One phone with 5.5inch screen. I'm having issue simiar to #602  but logged new issue as this is specific to Phone I believe.
System has normal font size but the battery voltage, mode and HDOP values all wrap around to second line. It seems there is enough space to fit the text but the whitespace border maybe needs to shrink? 
Even if I shrink to smallest font size it still appears to wrap to next line.

See attached screenshot.
![screenshot_2015-10-22-08-23-15](https://cloud.githubusercontent.com/assets/5005893/10679224/91b2513c-7973-11e5-8ecc-6f0e1a07a3fb.png)

**Comment by ggregory8** [comment]
Can we change the location of the warning messages. as currently if we have the drawer out (mostly always in my case) the message is hidden. Could dock the messages at bottom, just above Arm / Dronie buttons? Or alternatively make the warning text smaller and drop the top of the drawer down a little to allow the full message. Should I track this as a separate issue?

**Comment by ne0fhyk** [comment]
Fixed by pr #1727
