### ISSUE TITLE
Return to Me: Distance always same as Return to Launch

### ISSUE THREAD

**Issue by ggregory8** [DroidPlanner/Tower#1664]
Maybe I've understood this incorrectly but shouldn't if I select 'Return to Me' on the top bar it should display the distance from vehicle to Phone/Tablet GPS location? 

This appears to always show the distance from vehicle to home.

Also is this just for a distance indication? Or if 'Return to Me' is selected it will use your location for RTL?

**Comment by ne0fhyk** [comment]
Fixed by pr https://github.com/dronekit/dronekit-android/pull/391 and pr #1728
