### ISSUE TITLE
Crashed after connecting

### ISSUE THREAD

**Issue by busyStone** [DroidPlanner/Tower#1671]
Hi,

   My phone is android 5.1.1, i installed Tower-v3.2.1, after connected to the drone, Tower is crashed.

   I have a crash reporter with Tower-v3.2.0, looks like caused by TTS.

    java.lang.NullPointerException
    collection == null
    android.os.Parcel.readException(Parcel.java:1555)
    android.os.Parcel.readException(Parcel.java:1502)
    android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:700)
    android.speech.tts.TextToSpeech$11.run(TextToSpeech.java:1563)
    android.speech.tts.TextToSpeech$11.run(TextToSpeech.java:1560)
    android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2232)
    android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:742)
    android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:732)
    android.speech.tts.TextToSpeech.getAvailableLanguages(TextToSpeech.java:1560)
    org.droidplanner.android.notifications.TTSNotificationProvider.onInit(TTSNotificationProvider.java:371)
    android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
    android.speech.tts.TextToSpeech.access$1400(TextToSpeech.java:59)
    android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2146)
    android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2101)
    android.os.AsyncTask.finish(AsyncTask.java:636)
    android.os.AsyncTask.access$500(AsyncTask.java:177)
    android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5595)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ne0fhyk** [comment]
Fixed by commit ef2414651d533139231388955223b3caf96e88a8
