### ISSUE TITLE
Download offline maps led ANR problem

### ISSUE THREAD

**Issue by busyStone** [DroidPlanner/Tower#1673]
Hi,

   I want to download the offline map for a city, the map zoom level is probably 10. 

   I tap the button to trigger download, after awhile, there is no progress bar displayed, i try to move the map, then i got an ANR dialog.

   With debug, i found the urls need to download is 8 million.

   I think the execution time of MapDownloader.beginDownloadingMapID()  is too long in UI thread.

**Comment by ne0fhyk** [comment]
Fixed by pr #1726
