### ISSUE TITLE
Tower feature request

### ISSUE THREAD

**Issue by earldgrayjr** [DroidPlanner/Tower#1674]
History has been around for a while now in Tower, in the form of waypoints that one can step through. 

Any plans of making that history into a mission that could be edited and uploaded? Since tower can save, open, and edit missions.  it seems all the information is there in the logs on the device for a mission now. The information would just need to be reformatted as a mission. Open it up, edit out the messy parts.  add some Tower specific points (POI etc) and upload...  

Forgive me if this is a repeat...

**Comment by ne0fhyk** [comment]
Added in pr #1791
