### ISSUE TITLE
[Feature Request] - Full Video Activity with widgets and Telemetry data

### ISSUE THREAD

**Issue by guiseco** [DroidPlanner/Tower#1675]
![screenshot_2015-11-08-09-02-09](https://cloud.githubusercontent.com/assets/11425400/11020098/726be5c4-85fb-11e5-9450-297f867451ce.png)

**Comment by ontogmolomo** [comment]
what tower version is this?

**Comment by guiseco** [comment]
Sorry, this is a feature request !!!

**Comment by ontogmolomo** [comment]
Alright.

**Comment by ne0fhyk** [comment]
@guiseco the action bar telemetry info is already added in Tower v3.2.1 beta 1 which you can grab from https://play.google.com/apps/testing/org.droidplanner.android.beta.

**Comment by guiseco** [comment]
@ne0fhyk Very Nice !
