### ISSUE TITLE
FollowMe Radius cut off in Tower UI

### ISSUE THREAD

**Issue by zlite** [DroidPlanner/Tower#1679]
![screenshot_20151116-152950](https://cloud.githubusercontent.com/assets/18071/11198607/f09b05ee-8c7a-11e5-9bb6-98a0fca9da70.png)
In FollowMe mode on a Nexus 5x, the Radius line is cut off at the bottom of the FollowMe UI. (See attachment)

**Comment by lustek** [comment]
I confirm this bug. My device: motorola g 3rd gen, android 6.0

**Comment by ne0fhyk** [comment]
Fixed by PR #1716
