### ISSUE TITLE
Tower crashes when setting EKF_GPS_TYPE to 3

### ISSUE THREAD

**Issue by wilsonthongwk** [DroidPlanner/Tower#1682]
Here are so detail about my setup

- Tower version = 3.2.0
- ArduCopter firmware = 3.3.2-rc2
- tablet model = Samsung galaxy tab3 lite (SM-T113)
- tablet android version = 4.4.4

I use 915MHz telemetry radio to connect Tower with ArduCopter. I can successfully connect Tower to arduCopter and download all the parameter values. I then search for the EKF_GPS_TYPE. When I type "3" in the box, the Tower crashes.

Thanks,
Wilson

**Comment by ne0fhyk** [comment]
Fixed by commit 0e097f08ee3bc2d4ff10fce5f2aca1546398733b
