### ISSUE TITLE
How to set GimbalApi

### ISSUE THREAD

**Issue by tongzahub** [DroidPlanner/Tower#1684]
how to  set GimbalApi on button OnClick 

GimbalApi.getApi(dpApp.getDrone()).updateGimbalOrientation(90,90,90,null);
GimbalApi.getApi(dpApp.getDrone()).startGimbalControl(null);

**Comment by TShapinsky** [comment]
the listener passed to `startGimbalControl` must be non-null. Also you may want to store the GimbalApi in a variable so that you don't have to get a new one everytime you make an Api call.

**Comment by tongzahub** [comment]
could you show me some example for this case? thank you

**Comment by chaviw** [comment]
You can take a look at this class
https://github.com/DroidPlanner/Tower/blob/b47ef5305e5e91f9291bdb347a0462fc1524d49d/Android/src/org/droidplanner/android/fragments/widget/video/FullWidgetSoloLinkVideo.kt

It's in Kotlin but you should be able to figure out what it's doing. Essentially, the gimbal is manually controlled when the user touches the video stream view
