### ISSUE TITLE
droneplanner supported pixhawk

### ISSUE THREAD

**Issue by jilinggui** [DroidPlanner/Tower#1686]
hi guys,can you tell me which version of droidplanner can supports pixhawk or it is on the way? i am  forward to it .

**Comment by squilter** [comment]
The current version of Tower supports pixhawk running ArduCopter.

**Comment by jilinggui** [comment]
@squilter 
thanks,but someone say current  version is designed for apm,and support for PX4 is a little bit patchy,have you test it.

**Comment by squilter** [comment]
Yes, it is meant for ArduCopter.  It should work with PX4, but there might be problems.  If you do try it and run into problems, please do report them.

**Comment by jilinggui** [comment]
thanks again.but i am working on quadrotor.if there are some problem,i will report it .

**Comment by umfundi** [comment]
Tower works great with pixhawk.

**Comment by jilinggui** [comment]
@umfundi  thanks.
