### ISSUE TITLE
Altitude behavior 

### ISSUE THREAD

**Issue by gnobile** [DroidPlanner/Tower#1689]
A quick question to which I haven't found a proper answer: in follow me mode the altitude will remain constant within the actor? Or better: if the actor go downhill or uphill with say 30 meter altitude, this 30 meter will remain constant or Tower will not take care of the variation of the actor's altitude?

Thanks.

**Comment by ne0fhyk** [comment]
@gnobile Tower is not yet able to detect altitude changes because most Android devices don't support the functionality.
