### ISSUE TITLE
event Arm ,but don't need set DroneHome

### ISSUE THREAD

**Issue by tongzahub** [DroidPlanner/Tower#1694]
event Arm in Utils.java 

I need Arm ,But don't need set HomeDrone 
how to  solution

code in Utils.java 
public static void getArmingConfirmation(FragmentManager fm, final Drone drone){

		getActionConfirmation("arm", fm, new Runnable() {
			@Override
			public void run() {

				VehicleApi.getApi(drone).arm(true);

			}
		});
	}

 I want set event WayPoint ---> Land  and I want new Button RTL AUTO  {arm-take off , RTL mode }
but i have problem  DroneHome change

![untitled](https://cloud.githubusercontent.com/assets/12952880/12195780/61b263e6-b62c-11e5-91e6-321b735e12eb.jpg)

How to Arm ,But non set Drone Home sir?
Thank You

**Comment by tongzahub** [comment]
help me please!...

**Comment by ne0fhyk** [comment]
@tongzahub this is not the place for these type of questions. Can you instead ping the [dronekit-android gitter channel](https://gitter.im/dronekit/dronekit-android).
Once you do can you clearly explain what you're doing now, and its results and what you expect the results to be instead.
