### ISSUE TITLE
Change Speed question and suggestion

### ISSUE THREAD

**Issue by Wolf68k** [DroidPlanner/Tower#1699]
When doing a mission what is the default speed the drone will fly at?

Suggestion(2)
1. In the description for Change Speed can you add in what the default speed is?

2. Automatically setting the default setting in the Change Speed action to whatever the default speed is. What I mean is that as it is now when you make a Change Speed it defaults to 2.0. However if the default speed is let's say 15 then when you go to add a Change Speed it defaults to 15.0, then you'd have better idea of how much to adjust the speed to be lower or faster.

3. There's a setting in the main Settings for Default Altitude Value. How about one for Default Speed?

And I would think there would be a way to combine all of these suggestions at the same time.

**Comment by ne0fhyk** [comment]
Fixed by commit 918bd49bf4093ae20d0794f81f4392306180e485
