### ISSUE TITLE
Auto Take Off in Tower locks out controller right stick input

### ISSUE THREAD

**Issue by davefolts** [DroidPlanner/Tower#1702]
I just noticed I Sunday that after directing my Iris to auto take off, the Iris was not accepting pitch and roll input from the right stick on the stock radio controller.
After commanding LAND, the Iris returned and I had right stick input as well.
Further experimentation revealed No issues in a manual takeoff and full control after an auto takeoff from Tower IF I switched modes via the app.
Looked at the tlog and watched the parameters all update....I also noticed the "Pause" button in a depressed state in the Tower app when I had no right stick control.

**Comment by ne0fhyk** [comment]
@davefolts this is as designed since auto takeoff is only possible via the GUIDED or AUTO flight mode which both disables right stick input.
