### ISSUE TITLE
Survey does not work!

### ISSUE THREAD

**Issue by rsilmakuvaus** [DroidPlanner/Tower#1704]
Hey, I`m new here so I hope this comes to right place. Survey doesn`t draw aeria. Distance flight time  etc. shows 0,0. I have tried several times to reload app and trie diffrent phones and its always the same. Does anyone else have same broblem?

**Comment by CreativeBR** [comment]
It is happening here too. The flight altitude of the survey properties is red.

**Comment by wolkstein** [comment]
Same here,
flight altitude is red.
But If Tower is conected to an vihicle survey function works normal. So there is no way to create an survey offline.

**Comment by ne0fhyk** [comment]
@rsilmakuvaus Thanks for the bug report, I'll take a look at the issue.

**Comment by ne0fhyk** [comment]
The issue has been fixed and the fix will be released with the 3DR Services v1.5.2 release.
Thanks!

**Comment by ne0fhyk** [comment]
As a workaround, you can downgrade to the [3DR Services v1.5.0](https://github.com/dronekit/dronekit-android/releases/tag/3DRServices-v1.5.0.4) to recover the functionality.

**Comment by rsilmakuvaus** [comment]
Thousand thanks :)
Best regards hannu
23.2.2016 22.15 "Fredia Huya-Kouadio" <notifications@github.com> kirjoitti:
