### ISSUE TITLE
Photos taken out of the survey area (when approaching)

### ISSUE THREAD

**Issue by CreativeBR** [DroidPlanner/Tower#1705]
I have notice that when i draw a survey area that is not near to the home location all the way to this area is covered by photos (not only the survey area as i expected). 

When the quad end the survey area and return to home these extra photos are not taken.

**Comment by ne0fhyk** [comment]
@CreativeBR Thanks for the bug report. This issue is being fixed, and will be included in the 3DR Services v1.5.2 release.
