### ISSUE TITLE
Tower app crashes on Android 4.0.4 when no wifi

### ISSUE THREAD

**Issue by mariansoban** [DroidPlanner/Tower#1720]
Tower application always crashes on Android 4.0.4 while start when there is NO ACTIVE WIFI connection.
LOG:
[crash.log.txt](https://github.com/DroidPlanner/Tower/files/186018/crash.log.txt)
Fix: 
https://github.com/DroidPlanner/Tower/blob/develop/Android/src/org/droidplanner/android/utils/NetworkUtils.java#L53
`public static String getCurrentWifiLink(Context context) {`
`...`
`        final String connectedSSID = connectedWifi == null ? null : connectedWifi.getSSID().replace("\"", "");`
--->
`        final String connectedSSID = connectedWifi != null && connectedWifi.getSSID() != null ?  connectedWifi.getSSID().replace("\"", "") : null;`

Environment: Lenovo A660 with Android 4.0.4

**Comment by emerich68** [comment]
have the same problem in galaxy tab 10" & android 4.0.4.
Can you send me a compiled version with your correction (.apk)

**Comment by mariansoban** [comment]
Here you are. Please note, that the version contains my API key for google maps and is not official release.
[tower-release.3.2.0-sobi-3-bugfix_wifi.zip](https://github.com/DroidPlanner/Tower/files/199274/tower-release.3.2.0-sobi-3-bugfix_wifi.zip)

**Comment by emerich68** [comment]
it works , I can not setup mapbox id , but it works,
thanks a lot
we hope to be included in the official version

**Comment by ne0fhyk** [comment]
@mariansoban thanks for the bug report and fix! The fix will be included in the next beta release.
