### ISSUE TITLE
Waypoint altitude dialog defaults to 0.0m

### ISSUE THREAD

**Issue by rsilk1949** [DroidPlanner/Tower#1724]
When I select a waypoint which had the altitude changed in MP from the default e.g. 50m, the pop-up Waypoint window to modify the altitude shows the altitude as 0.0m even thought the list of waypoints at the bottom of the screen shows 60m.

**Comment by ne0fhyk** [comment]
Fixed by commit a33e96ae0ea90ca02902aa0e1da67c7e52b9f81b
