### ISSUE TITLE
Feature Request: Display altitude

### ISSUE THREAD

**Issue by rsilk1949** [DroidPlanner/Tower#1725]
None of the Flight Data UI widgets include the current altitude. IMO, this is basic info.

**Comment by ne0fhyk** [comment]
@rsilk1949 the current altitude is in the action bar on the bottom row in the center.

**Comment by rsilk1949** [comment]
I am using Tower-v3.2.0. I do not see any altitude displayed in the Flight
Data screen, only heading, roll, pitch, hs and vs.

**Comment by ne0fhyk** [comment]
Those are in the side right panel. Once you connect to a vehicle, the
action bar (top panel) inflates with additional telemetry data (I.e: GPS,
flight mode, distance to home, altitude, etc...).

On Wed, Mar 30, 2016, 1:18 PM rsilk1949 <notifications@github.com> wrote:

> I am using Tower-v3.2.0. I do not see any altitude displayed in the Flight
> Data screen, only heading, roll, pitch, hs and vs.
>
> On Wed, Mar 30, 2016 at 5:51 PM, Fredia Huya-Kouadio <
> notifications@github.com> wrote:
>
> > Closed #1725 <https://github.com/DroidPlanner/Tower/issues/1725>.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DroidPlanner/Tower/issues/1725#event-608565750>
> >
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/DroidPlanner/Tower/issues/1725#issuecomment-203614421>
>
-- 
◤Fredia Huya-Kouadio
    ANDROID TECH LEAD
    3D Robotics
    240.601.6575
    github <http://github.com/ne0fhyk> | google+
<https://plus.google.com/+FrediaHuyaKouadio>

**Comment by rsilk1949** [comment]
Thanks. I see it now :)

Robin

On 30 Mar 2016, at 9:54 pm, Fredia Huya-Kouadio <notifications@github.com> wrote:

Those are in the side right panel. Once you connect to a vehicle, the
action bar (top panel) inflates with additional telemetry data (I.e: GPS,
flight mode, distance to home, altitude, etc...).

On Wed, Mar 30, 2016, 1:18 PM rsilk1949 <notifications@github.com> wrote:

> I am using Tower-v3.2.0. I do not see any altitude displayed in the Flight
> Data screen, only heading, roll, pitch, hs and vs.
>
> On Wed, Mar 30, 2016 at 5:51 PM, Fredia Huya-Kouadio <
> notifications@github.com> wrote:
>
> > Closed #1725 <https://github.com/DroidPlanner/Tower/issues/1725>.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DroidPlanner/Tower/issues/1725#event-608565750>
> >
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/DroidPlanner/Tower/issues/1725#issuecomment-203614421>
>
-- 
◤Fredia Huya-Kouadio
ANDROID TECH LEAD
3D Robotics
240.601.6575
github <http://github.com/ne0fhyk> | google+
<https://plus.google.com/+FrediaHuyaKouadio>
