### ISSUE TITLE
Add wiki for setup of Uvc video stream

### ISSUE THREAD

**Issue by guiseco** [DroidPlanner/Tower#1730]
![screenshot_20160405-151944](https://cloud.githubusercontent.com/assets/11425400/14294603/553f9b72-fb48-11e5-899f-66729cefa5cb.png)
![screenshot_20160405-151948](https://cloud.githubusercontent.com/assets/11425400/14294604/554015b6-fb48-11e5-9460-12ef018e55a0.png)
![screenshot_20160405-151009](https://cloud.githubusercontent.com/assets/11425400/14294605/554fad5a-fb48-11e5-96aa-3d416a6dd8ef.png)
![screenshot_2015-10-04-12-33-12](https://cloud.githubusercontent.com/assets/11425400/14294656/82f30306-fb48-11e5-9653-b1905d54a6bc.png)
![p_20151107_202753](https://cloud.githubusercontent.com/assets/11425400/14294667/9121ca0c-fb48-11e5-85d7-6b593d9cc9e1.jpg)

**Comment by guiseco** [comment]
![41oc qwlfgl _sx425_](https://cloud.githubusercontent.com/assets/11425400/14992365/2ee94f86-113c-11e6-9288-8c4f0f7a9812.jpg)

**Comment by ne0fhyk** [comment]
Successfully completed by @guiseco!

**Comment by kikislater** [comment]
Is it possible to add chipset compatibility to the wiki ? I think chipset is more important than a link to aliexpress ...
Which chipset is onboard with the uvc white you reference on the wiki ? Does UTV007 will work ?
