### ISSUE TITLE
Screen rotation stops the video streaming

### ISSUE THREAD

**Issue by guiseco** [DroidPlanner/Tower#1731]
This behavior happens on KITKAT 4.4.2.

**Comment by ne0fhyk** [comment]
@guiseco does it stop all instances of video streaming (udp and uvc)?

**Comment by guiseco** [comment]
Just udp
Em 25 de abr de 2016 05:26, "Fredia Huya-Kouadio" <notifications@github.com>
escreveu:

**Comment by ne0fhyk** [comment]
@guiseco the issue should have been fixed in the newly release beta 6 for Tower: https://play.google.com/store/apps/details?id=org.droidplanner.android.beta.
Once you get a chance, can you check and see if you still encounter it.
