### ISSUE TITLE
Is there a way to convert the .dpwp to a text file or a way point file?

### ISSUE THREAD

**Issue by sw-rifai** [DroidPlanner/Tower#1732]
Hi, 
I am trying to link multiple flight paths together for an orthomosaic using a 3DR Solo. The trouble is that without being able to overlay the flight paths in QGIS, it's hard to tell if there are gaps in the targeted survey area that are not covered by each individual .dpwp flight file. I've seen other options to convert the file with a pixhawk, but I do not have one of these. Basically, a way to convert .dpwp to a text file would be of great use.
Thank you

**Comment by ne0fhyk** [comment]
Fixed by pr #1791
