### ISSUE TITLE
Assigning value to SYSID_THISMAV other than 1 causes 3DR Service stoppage in Tower when connecting

### ISSUE THREAD

**Issue by BigOkie** [DroidPlanner/Tower#1733]
To recreate, change the SYSID_THISMAV value to something other than 1 via MP or APM Planner (in my case I changed it to 128 since it was halfway inbetween the upper and lower range).  Opening Tower on the Android, then trying to connect would return a response about the 3DR Services stopping.  When I changed the SYSID_THISMAV value back to 1 it worked ok again.

**Comment by tribbloid** [comment]
+1, though I doubt if any android device have enough USB for that many downlinks. (non p2p WiFi? Never heard of it)

**Comment by ne0fhyk** [comment]
Closing at I'm not able to reproduce the issue with the latest beta for Tower.

**Comment by tribbloid** [comment]
Duh, you are not even using 3DR service now :)
