### ISSUE TITLE
Follow me distance stuck at 26 ft

### ISSUE THREAD

**Issue by conorman73** [DroidPlanner/Tower#1745]
We have been doing some flying using the "follow me" capability in the Tower App with an Iris running the latest version of arducopter. Follow me works as it should except for the fact that the wheel that is supposed to let us change the follow radius is not working. The vehicle follows me at a fixed distance of 26ft.  This issue is present in the 3DR Solo too, so it seems like it is a problem with the android app.

**Comment by ne0fhyk** [comment]
Fixed by commit c1ff7d7215d48ff88724bb651612b69be879712a
