### ISSUE TITLE
UVC widget doesn't show the video

### ISSUE THREAD

**Issue by fliegermati** [DroidPlanner/Tower#1747]
Hi,

i bought a uvc device with the arkmicro chip Form aliexpress. 
But when i connect it with a USB host Adapter  to the tablet i only see this:

![screenshot_2016-05-12-17-07-03](https://cloud.githubusercontent.com/assets/19329732/15219796/6868b69a-1865-11e6-90b8-2697297334a3.png)

![1463066343758-480077618](https://cloud.githubusercontent.com/assets/19329732/15219895/be5ad1be-1865-11e6-973e-b250b9148ed8.jpg)
![1463066816260-137761782](https://cloud.githubusercontent.com/assets/19329732/15220152/c3cf8f62-1866-11e6-9dc1-ea06e6d80603.jpg)
![1463066844542-670926835](https://cloud.githubusercontent.com/assets/19329732/15220160/d1aadbe6-1866-11e6-83ea-eb24d3e9ac1b.jpg)

I tried to power the USB host with a external power supply, without any effect.

Tower Version: 3.2.1 beta 7
3DR services: 1.5.3
Teclast x98 plus
Android 5.1

Is the UVC device broken?

Can anybody help me?

Fliegermati

**Comment by guiseco** [comment]
Do you have another tablet or cell phone to test ? Try connecting only UVC to your tablet.

**Comment by fliegermati** [comment]
Okay, without the usb host the uvc device works in Tower now! So i should connect the 433mhz groundstation with bluetooth to the tablet

**Comment by guiseco** [comment]
.. or try another USB hub -> http://www.ebay.com/itm/141564311626

**Comment by ne0fhyk** [comment]
@fliegermati I'm closing this issue, since it seems to be resolved.
