### ISSUE TITLE
Custom UDP video stream with raspberry pi and uvc device

### ISSUE THREAD

**Issue by fliegermati** [DroidPlanner/Tower#1751]
Hi,

the command for a custom video stream with a test file is:

gst-launch videotestsrc ! 'video/x-raw, width=1280, height=720, framerate=(fraction)24/1' ! x264enc ! rtph264pay ! udpsink port=<device_port> host=<device_ip>

I have a uvc device (ArkMicro) directly connected via USB to Tower app. But i want to a video stream without a cable to the tablet.
So i want to use a raspberry pi with gstreamer und the uvc device to stream a video wireless to the tablet.
I have tried serveral commands with gstreamer, but no one streams a video from a uvc device with udp.

Can anybody tell me a functioning gstream command to stream from /dev/video0 via UDP to tower widget?

Matthias

**Comment by ne0fhyk** [comment]
@fliegermati  this post on diydrones might help you with the information you need: http://diydrones.com/profiles/blogs/streaming-raspi-camera-video-to-tower-video-widget

That said, the best place to ask these  questions in the future would be the tower forum at http://discuss.ardupilot.org/c/ground-control-software/tower

-
