### ISSUE TITLE
Can't access tlogs and flight history

### ISSUE THREAD

**Issue by TheAeroScout** [DroidPlanner/Tower#1752]
Guys I've been upgraded to Tower 3.2.1 but I'm now having troubles finding the telemetry logs, I use them to geotag my photos post flight. There is no longer a 'flight history' tab and when I search there's no tlogs. Has this feature been taken away or am I just looking in the wrong location? Cheers.

**Comment by guyppp** [comment]
I also had this issue, but searching through the Device Storage on my Samsung S5, I found a collection of Tlogs here: Local Storage > Device Storage > Android > data > org.droidplanner.services.android > files> tlogs

**Comment by TheAeroScout** [comment]
Thanks, I'll check it out to make sure that's where they live.
It would be great to have the 'flight history' tab back (if possible) please, I really found it useful. An extra added feature would be to be able to export .tlogs from that screen, perhaps via email. Would make it nice and easy to get .tlogs from Android across to Mission Planner without having to plug in.
Cheers

**Comment by TheAeroScout** [comment]
I've found that if I turn off the Android device and then on again, the latest tlog appears. If I don't do the restart then it's not listed. Pleased that I can find them again, thanks for your help. :)

**Comment by ne0fhyk** [comment]
Flight history has been added through pr #1779, and will be included with the next Tower release.

**Comment by FLYBYME** [comment]
Well I really needed this the other day. Came to use it and it was gone. Why was it removed?

**Comment by ne0fhyk** [comment]
@FLYBYME UI and functionality revamp
