### ISSUE TITLE
Arming from Tower app causes full throttle, then flop to side or on back

### ISSUE THREAD

**Issue by PeterSprague** [DroidPlanner/Tower#1755]
Arming from Tower app causes full throttle, then flop to side or on back

I use Tower to pre-program and auto fly flights with my 3DR Solo.  Currently need to manually take-off, then choose auto in Tower to fly planned flight.

Tried rebooting everything numerous times.  This has been happening over the last week when I attempt to survey.

More minor issue is that the verbal responses often get into loops, repeating notifications or saying going to way point 1 right after it landed from an auto flight and shut down copter

**Comment by guyppp** [comment]
I had exactly the same issue a couple of days ago, seems an issue with the gyroscope...not sure if it's a calibration problem or if the solo needs to be launched from a completely flat surface. Am going to calibrate the compass and level before flying next time
