### ISSUE TITLE
Is it support if it is connected via Easycap device ?

### ISSUE THREAD

**Issue by kushanshah11** [DroidPlanner/Tower#1760]

**Comment by Genestealer** [comment]
I think you mean is the stk1160 EasyCap type android USB capture cards supported for video streaming, in a similar way to the UVC video stream?

**Comment by guiseco** [comment]
you can use a app called EasyCap Viewer and streaming video to Tower.

**Comment by ne0fhyk** [comment]
@kushanshah11 I'm closing this issue since you got the answer from @guiseco!

**Comment by kushanshah11** [comment]
@guiseco  i don't want to use EasyCap Viewer ,
i just want to know that Tower is supported stk1160 or utv007 ?

**Comment by kikislater** [comment]
It's usefull information. I don't understand why nobody want to answer in other thread also ! 
In my case I bought xyusb like recommandation. May be they don't test with these devices but it is sad they don't want to tell or share. For an open source software it is not common ...

**Comment by ne0fhyk** [comment]
@kikislater This community shares freely when it comes to information, so if no one is answering, it's more likely that no one has experiences with this specific hardware.
In that case, you can contribute as well by testing, and reporting your findings through edit to the [Tower wiki](https://github.com/DroidPlanner/Tower/wiki) :)

**Comment by ne0fhyk** [comment]
@kikislater This community shares freely when it comes to information, so if no one is answering, it's more likely that no one has experiences with this specific hardware.
In that case, you can contribute as well by testing, and reporting your findings through edit to the [Tower wiki](https://github.com/DroidPlanner/Tower/wiki) :)

In addition, the best place for this type of questions would be the [Tower forum](http://discuss.ardupilot.org/c/ground-control-software/tower).

**Comment by kikislater** [comment]
Thank you for Tower forum. I think we are not able to edit wiki, we have to create a fork and push a pull request

**Comment by ne0fhyk** [comment]
@kikislater The wiki should be editable by all github users without need to fork and submit a pull request. I just checked the settings to confirm it is. 
Can you try once more, and confirm you're able to edit/contribute to it.

**Comment by kikislater** [comment]
Ok it's available for editing, sorry !

**Comment by Genestealer** [comment]
I tried using EasyCap viewer and streaming to Tower however he's account viewer shuts down when it's sent to the background and tower is brought into the foreground in Android. I was hoping that we could add support for those devices to Tower.

**Comment by kikislater** [comment]
So it's not working as easy as XYUSB chipset ! 
Did you tried with another device? Some android device like my huawei close background app

**Comment by kushanshah11** [comment]
finally it is not supported if i use Easycap?

**Comment by kikislater** [comment]
It should work if you are able to stream video to tower but not as plug and play as xyusb chipset

**Comment by kushanshah11** [comment]
Have anyone know how to stream video using Easycap Device to Tower please let me know it would be helpful to me...

Thanks.

**Comment by pedvi7** [comment]
I can say for sure that I've tried Easycap, for some reason it won't stream to the latest beta Tower with guiseco updates. It does stream ok to Easycap viewer app on my S6edge and tab 10.
I'm still planning on getting one off those Chinese generic UVCs guiseco used, but it's going to take about a month.
Any suggestions?

**Comment by kushanshah11** [comment]
hi @pedvi7  i just want make one app that stream video using easycap device same as (Easycap viewer).
i search lot on it but didn't success.

if anyone have idea how to stream video from any RCA device please do needful.

Thanks.

**Comment by kikislater** [comment]
May be in Qgroundcontrol, it should be possible to stream from easy cap
