### ISSUE TITLE
tower app spun up props turning over quadcopter

### ISSUE THREAD

**Issue by goofyfoot2001** [DroidPlanner/Tower#1769]
hit the connect on 3dr usb and propellers spun up and flipped my quad breaking all carbon fiber propellers.  wtf  why would this app send commands on connect?

**Comment by goofyfoot2001** [comment]
apm 2.8  android note 3

**Comment by squilter** [comment]
What arducopter version?

**Comment by goofyfoot2001** [comment]
Will have to check when I get home.  Just updated though I think,

**Comment by squilter** [comment]
Also please include any logs

**Comment by goofyfoot2001** [comment]
Sorry, couldn't get to it last night. Will let you know when I get more
info.

Kevin

**Comment by ne0fhyk** [comment]
@goofyfoot2001 closing this for lack of update.

**Comment by goofyfoot2001** [comment]
sorry, just decided it was best to notnuse the app.
