### ISSUE TITLE
Tower can not run  on no gms services  cellphones in China?

### ISSUE THREAD

**Issue by offbye** [DroidPlanner/Tower#1775]
Tower can not run  on no gms services  cellphones in China?
Android phones in china not have Google services, so can not use Tower.
Do you have a plan to solve it ?

**Comment by Linjieqiang** [comment]
@offbye But you can use "fishDroneGCS飞鱼地面站".I will update it to Version 2.0 later.

**Comment by ne0fhyk** [comment]
@offbye Tower architecture is modular enough, that it's possible to replace Google services with an alternative. However, I currently lack the time and resources to attempt such a replacement, but would welcome external contributions to that effect.
