### ISSUE TITLE
Survey - Save settings

### ISSUE THREAD

**Issue by 0n3-70uch** [DroidPlanner/Tower#1776]
Hello,

is it possible to store the settings in survey mode? Like camera model, flight attitude and so on...

Thank you
Greetings
Fabian

**Comment by ne0fhyk** [comment]
@0n3-70uch yes, in the `Editor` screen, click on the menu overflow buttons (three vertical dots in the screen top right corner) to open the menu.
There should be an option to export your current mission to a file.
To restore the saved settings, just used the same menu to import the previously saved mission back.

**Comment by 0n3-70uch** [comment]
@ne0fhyk Hi, thanks for your fast answere. But that is not what I mean. Is it possible to save the curent (most used) camera model and the parameters like flight attitude, direction, ... So when I make a new survey the parameters are the same like before. At the Moment I must check each parameter, that is really time-consuming.

Greetings Fabi

**Comment by ne0fhyk** [comment]
Fixed by commit a947a7449fc61bf6779927794c4ef74a7a875f72

**Comment by 0n3-70uch** [comment]
Thank you.
