### ISSUE TITLE
Android Aug 5th Security patch now causes force-close when arming

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [DroidPlanner/Tower#1780]
I successfully used Tower on my Nexus 5x running the latest Android (6.0.1) up until today.

An Android security update applied last night now renders Tower unusable - I get a force-close every time I use the "Arm" feature. The drone arms, but then Tower crashes.

Happy to provide more system info if needed.

**Comment by ne0fhyk** [comment]
@AKAMEDIASYSTEM it's most likely you're running 3DR Services v1.6, which is the cause of the issue.

Unfortunately, there's nothing that can be done on our end as 3DR released a buggy version of 3DR Services. 
The best fix at the moment is to revert 3DR Services to version 1.5.3, and prevent any further updates.

We're working to break Tower's dependency on 3DR Services so this sort of issue will not repeat in the future.

Thanks.
