### ISSUE TITLE
Why I can not use channels 9 and 10? 

### ISSUE THREAD

**Issue by cuchara** [DroidPlanner/Tower#1796]
Why I can not use channels 9 and 10?
I try to use as channels 9 and 10 of the transmitter with the APM, but does not work. why?

![captura de pantalla 2016-08-24 a la s 12 01 02](https://cloud.githubusercontent.com/assets/21206828/17930959/35f2221e-6a09-11e6-8949-64c0d9aaa011.png)

**Comment by guiseco** [comment]
http://ardupilot.org/copter/docs/channel-7-and-8-options.html

**Comment by cuchara** [comment]
thanks for your answer.

>  (http://ardupilot.org/copter/docs/channel-7-and-8-options.html)

I already had read before ... but still do not understand ... is the same as I did, not?

**Comment by cuchara** [comment]
@ne0fhykne0fhyk closed this 5 hours ago   way ?

**Comment by guiseco** [comment]
APM cannot handle more than 8 channels. that´s it! Only PIXHAWK CAN !

============================================================
  ((
  )))
|''''''''''|-.    Sun Certified Java Programmer
|___|-'    Guilherme S. Blanco

============================================================

2016-08-24 16:38 GMT-03:00 cuchara <notifications@github.com>:

**Comment by cuchara** [comment]
Hi thanks for your answer. 

 HobbyKing Daily - HKPilot 32 Controller  should work as  PIXHAWK , no?

**Comment by guiseco** [comment]
Yes ! Is a Good FC !!!

Em 25 de ago de 2016 5:54 AM, "cuchara" <notifications@github.com> escreveu:

**Comment by cuchara** [comment]
So why I cannot handle more than 8 channels ?   : /
