### ISSUE TITLE
Error:Error: Fragments should be static such that they can be re-instantiated by the system, and anonymous classes are not static [ValidFragment]

### ISSUE THREAD

**Issue by Jim-uav** [DroidPlanner/Tower#1798]

**Comment by guiseco** [comment]
Thats lint error,  to disable aborting on errors, add:

lintOptions {
    abortOnError false
}

to build.gradle.

**Comment by Jim-uav** [comment]
It was already in it, but it didn't work.
![Uploading QQ截图20160826205144.jpg…]()

**Comment by Jim-uav** [comment]
It was already in it, but it didn't work.
![Uploading QQ截图20160826205144.jpg…]()

**Comment by ne0fhyk** [comment]
@Jim-uav what's this issue about? There's no description given.

**Comment by Jim-uav** [comment]
@ne0fhyk 
![image](https://cloud.githubusercontent.com/assets/10829026/18024187/19cd70a4-6c37-11e6-8b27-e900260d3400.png)

**Comment by bitdust** [comment]
also have the same problem

**Comment by Linjieqiang** [comment]
also have the same problem

**Comment by guiseco** [comment]
Same problem to me.

**Comment by bitdust** [comment]
i just solve it by add
"checkReleaseBuilds false"
in lintOptions

like this:
![image](https://cloud.githubusercontent.com/assets/6072743/18282070/05842dbe-7492-11e6-8fa2-fd7d8d6199c4.png)

**Comment by ne0fhyk** [comment]
Can you all try with the [`standalone`](https://github.com/DroidPlanner/Tower/tree/standalone) branch. I pushed an update that should also fix the issue.

**Comment by bitdust** [comment]
@ne0fhyk 
cool~it works.

**Comment by ne0fhyk** [comment]
Fixed by commit d0abadce17ed05415ea406b13036695d5149a217
