### ISSUE TITLE
flight time in mission editor do not recalculate the flight-time while changing speed with "change speed" command

### ISSUE THREAD

**Issue by wolkstein** [DroidPlanner/Tower#1805]
the flight-time of mission (top-right) will not updated if you use the change speed command.
flight time is every time the same. No recalculation if you change the speed with the do change speed command. For example to 18m/s. In the video you can see that the flight-time of the example mission stay at 48seconds. also if speed change. the time only changes if i remove way-points (shorten the mission)

video link:
https://www.dropbox.com/s/vfek7tzvmo7ulbb/2016-09-07%2022.38.56.mp4?dl=0

Tower Version is the current stable from Google Play.
/g
wolke

**Comment by ne0fhyk** [comment]
Fixed by pr #1815
