### ISSUE TITLE
How to run this project in AndroidStudio? 

### ISSUE THREAD

**Issue by luyuan11233** [DroidPlanner/Tower#1833]

**Comment by Linjieqiang** [comment]
First,you must have Android Studio.And this issue was board and no meaning.

**Comment by luyuan11233** [comment]
yes，i have it. but when i run it,it show me this question,
![ab29c2c3-6032-4dd4-bb1f-04466b903404](https://cloud.githubusercontent.com/assets/15043392/20659578/5a0c0162-b57f-11e6-91c7-3b848a8a01c4.png)
what to do next? i need your help.
thank you!

**Comment by luyuan11233** [comment]
and when i run it,it show follows
Error:(7, 0) Could not find method compile() for arguments [com.google.android.gms:play-services-location:9.4.0] on DefaultExternalModuleDependency{group='com.google.android.gms', name='play-services-maps', version='9.4.0', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
<a href="openFile:/Users/ruiyunitc/Downloads/Tower-develop/Tower-develop/Android/build.gradle">Open File</a>

is it outdated？so what should i do?

**Comment by heldib** [comment]
I am new here too and I am facing the same error above. Anyone can help?
"Error:(7, 0) Could not find method compile() for arguments [com.google.android.gms:play-services-location:9.4.0] ....

**Comment by billbonney** [comment]
You need to pick a build variant that you don't need to sign, i.e. devDebug. You open the window by clicking the Build Variant tab of the lower right-hand side
![buildvariant](https://cloud.githubusercontent.com/assets/959994/21253115/d85d831c-c310-11e6-84aa-94d3d925f3f2.png)

**Comment by heldib** [comment]
This fixed it for me. Thanks a lot!

**Comment by billbonney** [comment]
This Issue is closed and kept here for reference. Support is handled here for future http://discuss.ardupilot.org/c/ground-control-software/tower

We try and keep GitHub for issues that require a fix in the code. 👍 Thx
