### ISSUE TITLE
Wrong colour android 8

### ISSUE THREAD

**Issue by 0n3-70uch** [DroidPlanner/Tower#1871]
Hello, the colour of the menu is wrong with android 8 oreo.

![screenshot_20170904-075925](https://user-images.githubusercontent.com/6533600/30013462-09e3ff1a-9147-11e7-8198-742ff2e0b881.png)

**Comment by gmorph** [comment]
This has been fixed by this PR
https://github.com/DroidPlanner/Tower/commit/c6a636772389703aad5bd45c958c29a5fe311cb3
and can be closed.

**Comment by 0n3-70uch** [comment]
Thanks
