### ISSUE TITLE
Rotating copter +/- 90 degress in flight direction during waypoint mission

### ISSUE THREAD

**Issue by dl2ecc** [DroidPlanner/Tower#1877]
Hi all,
if I'm flying in a waypoint missing, it would be nice to rotate the copter in a +/- 90 degree angle
to the flight direction. The copter should stay in this angle during the whole missing.
This allows to fly over solar parks while taking infrared videos from solar panels.
This would be a nice feature for the next tower release.

Regards
Wolfgang

**Comment by gmorph** [comment]
This isn't a current issue with the code and is really a feature request so shouldn't be in the issues list but on the discussion forum instead.
Further ArduPilot already does this.  In your mission you need to specify a CONDITION_YAW command.  See the documentation here.
http://ardupilot.org/copter/docs/mission-command-list.html#mission-command-list-condition-yaw
Thanks, Grant.

**Comment by billbonney** [comment]
You can also set region of interest points along the route and copter will point at those.

Discussion can be had here https://discuss.ardupilot.org/c/ground-control-software/tower

**Comment by dl2ecc** [comment]
Hi Grant,

 

thanks for your answer.

I didn't know this function.

I'm going to test it in my next mission.

 

Best Regards

Wolfgang

 

Gesendet: Donnerstag, 02. November 2017 um 23:53 Uhr
Von: "Grant Morphett" <notifications@github.com>
An: DroidPlanner/Tower <Tower@noreply.github.com>
Cc: dl2ecc <dl2ecc@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [DroidPlanner/Tower] Rotating copter +/- 90 degress in flight direction during waypoint mission (#1877)


This isn't a current issue with the code and is really a feature request so shouldn't be in the issues list but on the discussion forum instead.
Further ArduPilot already does this. In your mission you need to specify a CONDITION_YAW command. See the documentation here.
http://ardupilot.org/copter/docs/mission-command-list.html#mission-command-list-condition-yaw
Thanks, Grant.

**Comment by dl2ecc** [comment]
Hi Bill,

 

thanks for your answer.

I try it in my next misiin.

 

Best Regards

Wolfgang

 

Gesendet: Freitag, 03. November 2017 um 00:01 Uhr
Von: "Bill Bonney" <notifications@github.com>
An: DroidPlanner/Tower <Tower@noreply.github.com>
Cc: dl2ecc <dl2ecc@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [DroidPlanner/Tower] Rotating copter +/- 90 degress in flight direction during waypoint mission (#1877)


You can also set region of interest points along the route and copter will point at those.
