### ISSUE TITLE
unknown flight mode Tower app 

### ISSUE THREAD

**Issue by vmv007** [DroidPlanner/Tower#1910]
When i connect my copter, Flight modes switch spontaneously from Stabilze to unknown flight mode............ 
I am using pixhawk cube orange arducopter 4 firmware. Pls help me with this issue
The same issue in droid planer 2

**Comment by RuffaloLavoisier** [comment]
Which `.APK` do you use for gcs app?

**Comment by vmv007** [comment]
ср, 10 нояб. 2021 г., 16:18 RuffaloLavoisier ***@***.***>:

**Comment by vmv007** [comment]
> Which `.APK` do you use for gcs app?

![Screenshot_20220123-174137_Tower Beta.jpg](https://user-images.githubusercontent.com/88681489/150686416-73f825f6-097b-4876-a9bc-f7b5d9e17108.jpg)

**Comment by RuffaloLavoisier** [comment]
@vmv007

https://github.com/DroidPlanner/Tower/releases/download/Tower-v4.0.0.10/tower-prod-release.400010.apk

Try using this. !

**Comment by vmv007** [comment]
> @vmv007
> 
> https://github.com/DroidPlanner/Tower/releases/download/Tower-v4.0.0.10/tower-prod-release.400010.apk
> 
> Try using this. !

Ok, thanks

**Comment by RuffaloLavoisier** [comment]
@vmv007 
Or [this is](https://cdn.down-apk.com/org.aerohawk.android/Mission%20Maker%20for%20ArduPilot_4.0.0_apkcombo.com.apk?ecp=b3JnLmFlcm9oYXdrLmFuZHJvaWQvNC4wLjAvNC45ZWQ2NjI1ZmE4MTEyYTdiN2ZmZWFmMjdmODU0ZTIxYWJmYmM3OGJhLmFwaw==&iat=1642953266&sig=f1590cda53299293429b6408f2dd7ef6&size=19911150&from=cf&version=latest)
