### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by ghost** [DroidPlanner/Tower#325]
As suggested by Arthur I post my suggestions for making survey planing even more perfect here. I extended the list a little. It is clear that it should not get too complex. So maybe some options might be better placed into an advanced options section.
- storing and automatically loading the camera and survey settings when switching back into planning mode (especially flight altitude and overlaps)
- allow for different altitude steps intervals (especially in low altitudes): 0-10m in 1m steps, 10-50 in 5 m steps, 50-100 m in 10m steps, 100-1000 in 50 m steps
- synchronizing the maps of the planning and flight data screens and show the same extent when switching between them
- implementing CAM_TRIGG_DIST and WPNAV_SPEED using sliders (and report resulting flight time)
- WPNAV_SPEED might also be set automatically according to the survey/camera data if a minimum shooting interval [s] of the camera is provided by the user (or maybe the *.xml file). Additionally, the user should be able to adjust it manually (especially to lower the calculated speed). 
- an option to change the "Yaw behavior during mission (WP_YAW_BEHAVIOUR)" would be helpful. For post processing/as well as visual inspection of the image set it would be good if the yaw is set fixed to the "Hatch angle" of the survey grid (i.e. from "Face next waypoint" or "Face along GPS course" to "Never change yaw") once the copter is on its way between WP1 and WP2 (for sure this only makes sense for copters and I am not sure if this is possible at all during a mission),

**Comment by russdelaneyuk** [comment]
Hi
I am fairly new to the forum, so may be posting in the wrong place?
We survey large areas of land and I have a question? Drawing around the area to be surveyed is superb, is there a way to have a battery flight time set so if a large area is created, it will RTH for battery change and then continue the survey where it left off?
