### ISSUE TITLE
Flight modes not being recognized

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/Tower#518]
From Randy at drone-discuss:

> There’s a report on this thread that Droid Planner is not displaying the flight modes for AC3.1.  Could you check this out and confirm that it’s ok?
> http://diydrones.com/group/arducopterusergroup/forum/topics/apm-3-1-and-all-flight-modes-unknown

**Comment by getamu** [comment]
I am always getting the HOLD in failsafe menu and I am unable to change it using the tx. Can someone help me to solve this issue?
