### ISSUE TITLE
User editable telemetry boxes

### ISSUE THREAD

**Issue by markvanhaze** [DroidPlanner/Tower#633]
It would be useful to have the telemetry boxes ( on DPv2) editable by the user, so you could display the ones you want to show, for example longitude and latitude values of the current location of the aircraft.

Proposed data to be shown:
* [ ] Wind Speed and Direction

**Comment by empatid** [comment]
Where can i see just latitude and longitude of current location in flight screen? I couldnt find it.

**Comment by guiseco** [comment]
Me too!

**Comment by ne0fhyk** [comment]
Supported in version 3.2.0
