### ISSUE TITLE
Auto Mission Assistant

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/Tower#754]
The mode detail fragment for auto missions should aid the user during an auto missiom. Some of the possible features are:
- [ ] Progress bar
- [ ] Estimated time to finish
- [ ] Distance to finish
- [ ] Sumary of next waypoint
- [ ] Buttons to rewind/advance/pause the mission

**Comment by ne0fhyk** [comment]
Fixed by pr #1538
