### ISSUE TITLE
Flight actions for non-APM autopilots

### ISSUE THREAD

**Issue by brad112358** [DroidPlanner/Tower#919]
Part of getting DroidPlanner working on the AR Drone requires the ability to send it commands such as takeoff, land, loiter, return to home, etc.  Looking at the code (FlightActionsFragment.java), I see that the APM seems to use APM specific MAV_MODE for this functionality while the AR Drone expects a MAV_CMD sent via a COMMAND_LONG message.  I'm opening this issue to discuss the best way to implement support for both before I prepare a pull request.

We could, of course, just add conditional code which checks a flag or configuration setting to determine which style is required.

But I was wondering if any harm would be done if we just send both types of messages.  Will the APM ignore what it doesn't understand?  I'm sure that's what the AR Drone will do.  Since these messages would be sent only because of user interaction with menus or buttons on the screen, they won't be sent very often so the wasted bandwidth should be small.

Thoughts?

**Comment by ne0fhyk** [comment]
This is being implemented in 3DR Services.
